### ISSUE TITLE
Does this create a systemd service on linux?

### ISSUE THREAD

**Issue by MattL0** [marcus-j-davies/Homekit-Device-Stack#12]
Hi, 

I didn't play with this yet. I am just curious, will this create a systemd service on linux. 

If no what do you recommend? Thanks

**Comment by marcus-j-davies** [comment]
Hi Matt,

it does not create one by its self.

Use this template however, adjusting the user where needed (I use root) 

```
[Unit]
Description=HomeKit Device Stack
Wants=network.target

[Service]
ExecStart=/usr/bin/node App.js
User=root
Group=root
WorkingDirectory=/root/node_modules/homekit-device-stack

[Install]
WantedBy=multi-user.target
```
