### ISSUE TITLE
HTTP API - always get "Unauthorized" error

### ISSUE THREAD

**Issue by medicus07** [marcus-j-davies/Homekit-Device-Stack#6]
Hi there and thanks for the great project...

I configured some devices, output to NodeRed is working fine.

Over HTTP API input I always get an "Unauthorized" error, tried NodeRed and several browsers. Also tried the standard user/password and a self-defined password, same  issue.

e.g.
http://IP-RASPBERRYPI:7989/admin-SETPASSWORD/accessories

In terminal I get an error:  Could not send HTTP request : Error: socket hang up

Any ideas?

**Comment by medicus07** [comment]
The correct syntax is as follow:

http://IP-RASPBERRYPI:7989/SETPASSWORD/accessories

**Comment by marcus-j-davies** [comment]
Hi,

Sorry for the late response.
yeah, my bad for the confusion when I refer to **admin-password**

what I mean is the password that was set.

glad you worked it out.
